### ISSUE TITLE
Not a single php tag in your php files

### ISSUE THREAD

**Issue by martinczerwi** [martinox/mthielsch#1]
See this https://github.com/martinox/mthielsch/search?utf8=%E2%9C%93&q=php.

Might make sense to use html

**Comment by martinox** [comment]
This commit should fix the issue 
d88540bfd8ba2820c67d044e7750feba968fa64d

**Comment by martinczerwi** [comment]
Not sure, still parsed by PHP

**Comment by martinox** [comment]
Yes, this might be a problem.
Would you recommend using the .php extension as a html mimetype in apache?
Could there be any drawbacks?

**Comment by martinczerwi** [comment]
On another thought, I've fixed this #2

**Comment by martinox** [comment]
![unbelievable](http://i.giphy.com/12EUW4tMHW8cOQ.gif)
